### ISSUE TITLE
protocol Phoenix.Param not implemented for [locale: "en", page: 1]

### ISSUE THREAD

**Issue by abderrahmaneayad** [mgwidmann/scrivener_html#10]
I changed the router to add the locale, and it looks like this:

    scope "/:locale", App do
        pipe_through [:browser, :browser_session]

        get "/page", PageController, :index

        resources "/products", ProductController
    end`

when I inject the "locale: :en" in the pagination_links:

    <%= pagination_links @conn, @page, distance: 5, next: ">>", previous: "<<", first: true, last: true, locale: "en" %>

I got this error:

    protocol Phoenix.Param not implemented for [locale: "en", page: 1]

**Comment by mgwidmann** [comment]
Could you give a full stack trace?

I believe its making a call to `page_path(conn, :index, locale: "en", page: 1)` when in fact it needs to be calling instead `page_path(conn, :index, ["en"], page: 1)`.

**Comment by mgwidmann** [comment]
Nope, nevermind. Your call to pagination links is wrong.

Just like the phoenix call:

`<%= page_path @conn, :index, ["en"] %>`

Your `:locale` parameter needs to be passed in to correctly generate the link. So you'll need to do the same when you call `pagination_links/3`.

`<%= pagination_links @conn, @page, ["en"] %>`

I'll try to update the README to reflect this and so its more clear. If this doesn't solve your issue, please let me know.
