### ISSUE TITLE
page link always generated even through there are only one page

### ISSUE THREAD

**Issue by feixionglee** [mgwidmann/scrivener_html#19]
page link always generated even through there are only one page

**Comment by mgwidmann** [comment]
Could you please provide an example?

**Comment by feixionglee** [comment]
defp deps do 
      [
        ...
        {:scrivener_ecto, "1.0.0-dev", git: "https://github.com/drewolson/scrivener_ecto.git"},
        {:scrivener_html, "1.0.10", git: "https://github.com/mgwidmann/scrivener_html.git"}]
    end

My action:

    def index(conn, params, user) do
      query =  from(p in Post, preload: [:user, comments: [:user]])
      page = query
        |> Repo.paginate(params)

      render conn, "index.html",
        posts: page.entries,
        page: page,
        page_number: page.page_number,
        page_size: page.page_size
        total_pages: page.total_pages,
        total_entries: page.total_entries
    end

then I call `<%= pagination_links @conn, @page %>` in my **index.html.eex** template. even through there no records, the 1⃣️ always show.

**Comment by mgwidmann** [comment]
Well, its on page 1 is it not? Even if theres no data on the first page, thats what the pagination links should show. I don't think its good usability to hide the links do you?

**Comment by mgwidmann** [comment]
Would you show me the HTML it generates, maybe I'm not following fully...

**Comment by feixionglee** [comment]
`<nav><ul class="pagination"><li class="active"><a>1</a></li></ul></nav>`

The problem is the posts list is empty, so I think we should not generate any pagination links

**Comment by mgwidmann** [comment]
The above html indicates you're on page one and there are no other pages. We can't hide the number 1 as we still want to indicate that to the user. If we hide the links they may not realize that there's no data.

Why would we hide the number 1? This is an intentional feature, not a bug.

**Comment by feixionglee** [comment]
OK, understand it, thanks for your help.

**Comment by feixionglee** [comment]
could we provide a option to let user to hide it conveniently?

**Comment by mgwidmann** [comment]
```elixir
<%= if @posts != [] %>
  <%= pagination_links @conn, @page %>
<% else %>
   There are no pages!
<% end %>
```
