### ISSUE TITLE
Use scrivener 1.2.x's implementation of Enumerable for Scrivener.Page

### ISSUE THREAD

**Issue by schwarz** [mgwidmann/scrivener_html#21]
In a recent version scrivener added their own implementation for Enumerable https://github.com/drewolson/scrivener/pull/33. This module duplication blocks releases with current versions of both libraries.

**Comment by mgwidmann** [comment]
Oh nice! Great, glad they've added it!

So if I'm understanding right, I just need to remove my duplicate implementation? Do you know any way to conditionally implement it if it exists since I don't know what version of scrivener is being used...

**Comment by guofei** [comment]
what about assert_impl!(protocol, base)?

**Comment by mgwidmann** [comment]
Yes, but it raises an error... Hmm... I don't really like catching that at compile time...

**Comment by mgwidmann** [comment]
I've removed the protocol implementation and required scrivener `1.2` instead. This has been released as `1.1.1` for use with Phoenix `1.2-rc0` and `1.0.11` otherwise.
