### ISSUE TITLE
Support Scrivener 2?

### ISSUE THREAD

**Issue by jerodsanto** [mgwidmann/scrivener_html#27]
Howdy Matt,

Thanks for creating this, I've been using it with much success!

I'm curious what your thoughts are on supporting Scrivener 2. I'm upgrading my Phoenix app to all the latest and `scrivener_html`'s dependency on `scrivener ~> 1.2`, which depends on `ecto ~> 1.1` has become a show stopper for me.

Happy to help however I can!

**Comment by mgwidmann** [comment]
Merged PR, closing this issue.
