### ISSUE TITLE
Add phoenix_html 2.3 support

### ISSUE THREAD

**Issue by TakteS** [mgwidmann/scrivener_html#3]
The upgrade to new phoenix (1.1) fails with error:

Looking up alternatives for conflicting requirements on phoenix_html
  Activated version: 2.3.0
  From mix.exs: ~> 2.3
  From scrivener_html v1.0.0: ~> 2.2.0

** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

**Comment by mgwidmann** [comment]
Ah great. Would you submit a PR?
