### ISSUE TITLE
how to display query params in paginator links

### ISSUE THREAD

**Issue by prashantham** [mgwidmann/scrivener_html#31]
This <%= pagination_links @conn, @todos %> displays only the page parameter but other parameters are not listed

**Comment by mgwidmann** [comment]
Theres an example of how to do this in the Readme: https://github.com/mgwidmann/scrivener_html#example-usage

**Comment by prashantham** [comment]
params are not included even if i did <%= pagination_links @conn, @todos, [], path: &todo_path/3 %>

**Comment by mgwidmann** [comment]
If you do `<%= pagination_links @conn, @todos, some_other_url_parameter: "foo" %>` you should see your links end with `?page=2&some_other_url_parameter=foo` as is shown in the example.

[I've added a test to check this.](https://github.com/mgwidmann/scrivener_html/blob/master/test/scrivener/html_test.exs#L215)

**Comment by prashantham** [comment]
Is there a way to just pass in the query params?

**Comment by mgwidmann** [comment]
Should be able to just put it at the end of the function call like any other.
```elixir
<% params = [some: "url", parameter: "goes here"] %>
<%= pagination_links @conn, @todos, params %>
```
