### ISSUE TITLE
Scrivener.Html is not available in production

### ISSUE THREAD

**Issue by feixionglee** [mgwidmann/scrivener_html#34]
Hi, I get this error in my production machine, which deployed with edeliver.

I had to add :scrivener_html into my applications list in `mix.exs` to resolve it. 
```
def application do
  ...
  applications: [..., :scrivener_html, ...]
end
```
could we add some tips in README?

**Comment by mgwidmann** [comment]
Thats true for any dependency really, since it I believe exrm will strip out any dependency not in the applications list. If you wouldn't mind could you submit a PR to update the README?

**Comment by feixionglee** [comment]
ok, i am glad to do this
