### ISSUE TITLE
Generating links for non-REST paths

### ISSUE THREAD

**Issue by miskolc** [mgwidmann/scrivener_html#36]
It would be nice if you could include in the documentation an example for using `scrivener_html` when you don't do pagination on the `index` action of a controller.
I a route in my routes file like this
```
  scope "/", AppName do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/shops", PageController, :shops
    ...
  end
```

I wanted to use the pagination on the shops page but I had only the `page_path` helper that would generate links sending me to the `index` action instead of the `shops` actions

`<%=  pagination_links @conn, @page, path: &page_path/3 .... %>`

I could have easy created a new controller for the Shops resources and use it's `index` action but since I'm lazy I've found an easier solution:

Give the shops resource it's own path name using the `as:` option:
```
  scope "/", AppName do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/shops", PageController, :shops
    ...
  end
```

This will enable us to use the `shops_path` helper in our templates:

`<%=  pagination_links @conn, @page, action: :shops, path: &shops_path/3 .... %>`

Note that we also need to pass the `action` option to the `pagination_links` helper, since the method will default to the `:index` action.

And that's it.
I really hope it will be useful to other people. It took me some time to figure out how to get this right but I think is a use case that will reoccur time and time again.

**Comment by mgwidmann** [comment]
I would be happy to accept a PR to add this to the README

**Comment by mgwidmann** [comment]
Let me know if theres anything confusing or you think still needs adding! Thanks!
