### ISSUE TITLE
protocol Phoenix.Param not implemented for [page: 1]

### ISSUE THREAD

**Issue by yamzalal** [mgwidmann/scrivener_html#37]
I have added the following in my template

`<%= pagination_links @conn, @posts, path: &profile_path/3, action: :videos %>`

My function in the controller looks like below

```
def videos(conn, params) do
    user_id = params["user_id"]
    user = load_user(user_id)
    posts = Post
            |> where([p], p.user_id == ^user.id)
            |> where([p], p.type == 1)
            |> order_by(desc: :inserted_at)
            |> preload([{:user, :personal_detail}])
            |> Repo.paginate(params)
   render(conn, "videos.html", posts: posts, user: user,)
end
```

Routes for the videos is http://localhost:4000/profiles/1/videos/?page=1

```
scope "/", SampleProject do
    pipe_through [:browser, :require_authentication]
    get "/profiles/:user_id/videos", ProfileController, :videos
end
```

I get this error:

`protocol Phoenix.Param not implemented for [page: 1]`

**Comment by mgwidmann** [comment]
Hmm ok. I'm not sure what's different here. It will be at least a week before I can take a look. A PR would be welcome if you wanted to dig in yourself.

**Comment by mgwidmann** [comment]
Can you try using `profile_path/4` please? I suspect you're just providing the wrong function, if this is the problem I'll put a note on the REAEME.

**Comment by mgwidmann** [comment]
Any update on if `profile_path/4` fixed your issue?

**Comment by mgwidmann** [comment]
Closing this for now. Let me know if this is still an issue!

**Comment by yamzalal** [comment]
sorry for the delay in my reply and thanks for your efforts. Not sure this is the right way, but this is how i have fixed the issue. Manually added paginations variables in the render function.

`render(conn, "videos.html", posts: posts, user: user, page_number: posts.page_number, total_pages: posts.total_pages, total_entries: posts.total_entries)`

Created a custom function

```
def custom_pagination_links(total_pages, page_number, total_entries) do
      # print pagination only when total entries is more than 6
      if total_entries >= 6 do
        Scrivener.HTML.pagination_links(%Scrivener.Page{total_pages: total_pages, page_number: page_number}, view_style: :bootstrap_v4)
      end
    end
```

In template file, called the function
`<%= custom_pagination_links(@total_pages, @page_number, @total_entries) %>`
