### ISSUE TITLE
Can't use html entities in :next and :previous texts

### ISSUE THREAD

**Issue by Blackrush** [mgwidmann/scrivener_html#38]
Screenshot generated with this code : 

```elixir
Scrivener.HTML.pagination_links(var!(assigns)[:conn], var!(assigns)[:page], next: "&rightarrow;", previous: "&leftarrow;", view_style: :semantic, path: fn(conn, action, params) -> admin_resource_path(conn, action, var!(assigns)[:conn].params["resource"], params) end)
```

![screenshot from 2016-09-15 19-15-15](https://cloud.githubusercontent.com/assets/1549486/18559711/d4131112-7b78-11e6-9716-f95c7dddf821.png)

Using `{:scrivener_html, "~> 1.3"}`

**Comment by mgwidmann** [comment]
This is really a phoenix thing I believe... If you do `{:safe, "&leftarrow;"}` does it work? I can look into doing that automatically as well.

**Comment by mgwidmann** [comment]
Let me know if that commit fixes your issue.
