### ISSUE TITLE
Add links to first/last pages

### ISSUE THREAD

**Issue by TakteS** [mgwidmann/scrivener_html#44]
Hello. I think it would great if we had links to last and first pages, like this:
![2016-12-29 02-05-12](https://cloud.githubusercontent.com/assets/7054944/21526958/a80af0f6-cd73-11e6-9c79-8696b9f9a61a.png)

By default it may be disabled, and can be enabled, for example with option like: `recent_pages: true`.

Also, I think about ability to configure links styles by options:
```
= pagination_links @page, previous_class: "some css class", next_class: "..."
```

and the same for last/first links. 

What do you think about this? I think with these features we be able to easy pagination customize. 

Thank you!

**Comment by mgwidmann** [comment]
I'm not sure I understand. We do support first and last pages which is tested here:
https://github.com/mgwidmann/scrivener_html/blob/master/test/scrivener/html_test.exs#L84-L114

You can also supply your own by saying `first: "<", last: ">`

Are you suggesting including recently visited pages in the list?

**Comment by mgwidmann** [comment]
Correction... We do hardcode first to be `1` here:
https://github.com/mgwidmann/scrivener_html/blob/master/lib/scrivener/html.ex#L321

So then all we'd need to do is do like I suggested and allow `first: "<", last: ">"`... Shouldn't be too hard to support that.

**Comment by TakteS** [comment]
No, I'm not about recently visited pages :) I'm not saw `first: true` and `last: true` in readme, sorry.

And what about ability to configure CSS styles for each type of elements? Like:

```
first_class: "button-primary first",
last_class: "button-primary last",
active_page_class: "...",
```
and so on.

Or maybe it can be configured in `config.exs`:

```
config :scrivener_html, :css_styles,
  first_page: "...",
  active_page: "..."
```

**Comment by mgwidmann** [comment]
Well if I change it to allow a non-boolean like I proposed you'd be able to do something like `first: render_first(), last: render_last()` as long as those functions return either a string or an IO list it should work just fine. As for being able to change the classes of the `li` surrounding the first and last... What exactly is the use case for that?
