### ISSUE TITLE
Elixir 1.4

### ISSUE THREAD

**Issue by nlap** [mgwidmann/scrivener_html#50]
Looks like Keyword.merge raises in Elixir 1.4 if both args aren't keyword lists: https://github.com/elixir-lang/elixir/issues/5395

`params_with_page = Keyword.merge(url_params, [{page_param, page_number}])` breaks in html.ex with `expected a keyword list as the second argument, got: [{"p", 1}]`

**Comment by mgwidmann** [comment]
Oh yeah 😞 

I would love a PR if you have the time 😄

**Comment by nlap** [comment]
For sure, I'll take a look!

Seems strange, I mean `[{page_param, page_number}]` is technically a keyword list right? Maybe the problem is on Elixir's side.

**Comment by mgwidmann** [comment]
Nope its not. I think its referred to as a "property" list by erlang developers. Its only because the "key" is a binary instead of an atom... But I dont think making it into an atom is the solution, it may be best to just convert it to a map in the beginning and then always use that.

**Comment by nlap** [comment]
Ah, good to know. I'll see what I can do, but yeah, changing to Map is probably the cleanest.

**Comment by nlap** [comment]
FYI, I don't think I'll be able to find time to work on a PR for this 😞
