### ISSUE TITLE
User can set page querystring higher than total pages

### ISSUE THREAD

**Issue by dipth** [mgwidmann/scrivener_html#51]
Resulting in the helper rendering as many page links as the page number.
For instance, here I tried entering the page number `100` even though there is only 11 pages in total:

![screen shot 2017-02-22 at 00 16 39](https://cloud.githubusercontent.com/assets/171490/23189648/37d04ab0-f894-11e6-8ec7-2eb3bb6401f2.png)

At first sight this might just seem like a minor inconvenience for the user, but you could also enter a really high number like say `9999999999` which would make the backend try to render that many page links, causing the elixir process to hang. Do this enough times and you have an easy way to DDOS the site.

**Comment by mgwidmann** [comment]
Hmm ok, I'll have to add a test to check for this then

**Comment by mgwidmann** [comment]
Theres a PR opened to fix this issue now, thanks for reporting!

**Comment by mgwidmann** [comment]
Released in `v.1.6.0`, thanks!
