### ISSUE TITLE
Adding "rels" for SEO

### ISSUE THREAD

**Issue by JustMikey** [mgwidmann/scrivener_html#56]
I wonder if it makes sense to add `rel="next"` and `rel="prev"` for better SEO?

**Comment by mgwidmann** [comment]
Yeah sure, I'd be willing to accept a PR if you have the time...

**Comment by mgwidmann** [comment]
So I've got a PR opened at #59 if you wouldn't mind taking a look and telling me if you think it'll suit your use case enough.
