### ISSUE TITLE
disable link for current page

### ISSUE THREAD

**Issue by maierru** [mgwidmann/scrivener_html#62]
Is there any way to disable link 'a href' for current page?

**Comment by mgwidmann** [comment]
Sorry I missed this. What view implementation are you using and can you provide an example of the HTML you want vs what is actually produced? It should automatically not create a link for the current page, so I'm a bit confused as to what you mean.

**Comment by dsandstrom** [comment]
Disable the hover state of the active link.  Example for the `semantic` view style:
```css
.pagination .active {
  pointer-events: none;
}
```

**Comment by mgwidmann** [comment]
I believe I'm finally following what this means. Heres a test which shows we do put an `href` on the `active` anchor tag:
https://github.com/mgwidmann/scrivener_html/blob/de926e2cbd5cb77b60067590f62e53fce100d674/test/scrivener/html_test.exs#L266

**Comment by mgwidmann** [comment]
Master is updated with this commit https://github.com/mgwidmann/scrivener_html/commit/278e6a975a13a2828809698b54432b2bac055e7f
Could you take a look and let me know if it suits your needs?
