### ISSUE TITLE
Option to disable pagination when results are on single page

### ISSUE THREAD

**Issue by ArturT** [mgwidmann/scrivener_html#65]
Would be nice to have an option to don't show the pagination when there is only 1 page with results.

Example how it could work:

```
<%= pagination_links @page, hide_when_single_page: true %>
```

and it would render nothing.

**Comment by mgwidmann** [comment]
Could you not do that with `if @page.total_pages == 1`?

**Comment by ArturT** [comment]
I could use `if` but then I will have to add it everywhere where I use pagination.

It would be nice to configure it once like:

```
config :scrivener_html,
  hide_when_single_page: true
```

But if it doesn't make sense then we can close this issue.

**Comment by mgwidmann** [comment]
I think in your case you should make a pagination partial and put your logic there. That is not a feature this project needs.
