### ISSUE TITLE
bootstrap 4 support?

### ISSUE THREAD

**Issue by ulutomaz** [mgwidmann/scrivener_html#68]
Hi,

any plans for Bootstrap 4 support. Design for pagination links is broken. 

Best,
Tomaz

**Comment by mgwidmann** [comment]
Bootstrap 4 is supported in the README https://github.com/mgwidmann/scrivener_html#view-styles 

If theres something broken, I'd appreciate a PR fixing the changes!

**Comment by jwipeout** [comment]
I also tried the pagnation and it is missing some classes that are being used. I will try to create a pr. 

```html
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>
```
