### ISSUE TITLE
Update for phoenix 1.4.0

### ISSUE THREAD

**Issue by hlongvu** [mgwidmann/scrivener_html#77]
Phoenix 1.4.0 has now released: https://phoenixframework.org/blog/phoenix-1-4-0-released
Hope you update this repo soon :)

**Comment by hlongvu** [comment]
If anyone wants a quick fix before the update arrives, you can use this:

```
defp deps do
[
  {:scrivener_html, git: "https://github.com/hlongvu/scrivener_html.git"}
]
```

I just bump the version of phoenix to < 1.5.0 as pull request above.

**Comment by tielur** [comment]
@mgwidmann any chance this can be merged and hex.pm updated soon?

**Comment by mgwidmann** [comment]
My apologies, I'll address this tonight.
