### ISSUE TITLE
Bug in find_path_fn

### ISSUE THREAD

**Issue by l-vincent-l** [mgwidmann/scrivener_html#84]
I'm trying to understand this line :

https://github.com/mgwidmann/scrivener_html/blob/master/lib/scrivener/html.ex#L152
 ```path = path_args |> Enum.reduce(name_for(List.first(entries), ""), &name_for/2)```
It calls name_for which is a one liner:
 ```"#{acc}#{if(acc != "", do: "_")}#{Phoenix.Naming.resource_name(model.__struct__)}"```
and I don't understand why `path_args` has to be a model.

Am I missing something ?

**Comment by mgwidmann** [comment]
Hmm, not sure I remember to be honest. What is it you're having an issue with? Is there an exception you're receiving?

**Comment by mgwidmann** [comment]
Closing as this hasn't seen any traction in a long time.
