### ISSUE TITLE
Milligram view styles?

### ISSUE THREAD

**Issue by spapas** [mgwidmann/scrivener_html#88]
It seems that phoenix now uses milligram for creating its html views. I guess that a milligram view style would  be an excellent addition to this project.

**Comment by mgwidmann** [comment]
I'd be willing to accept a PR for this if you'd like.

**Comment by spapas** [comment]
Hello @mgwidmann unfortunately it seems that milligram doesn't have any pagination components so this can't be implemented until they provide such functionality.

However, for users having this problem I have written a couple of css styles that should output properly styled pagination links when you use the `bootstrap_v4` view style in your config:

```
.pagination .active {
  pointer-events: none;
}

.page-item:first-child .page-link {
  margin-left: 0;
  border-top-left-radius: .25rem;
  border-bottom-left-radius: .25rem;
}
.page-link:not(:disabled):not(.disabled) {
  cursor: pointer;
}
.page-link {
  position: relative;
  display: block;
  padding: .5rem .75rem;
  margin-left: -1px;
  line-height: 1.25;
  color: #007bff;
  background-color: #fff;
  border: 1px solid #dee2e6;
}

.pagination {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  padding-left: 0;
  list-style: none;
  border-radius: .25rem;
}
```

**Comment by mgwidmann** [comment]
Ok, should we close this then?

**Comment by spapas** [comment]
@mgwidmann yes probably, i'm not really sure if the milligram css framework will ever add pagination components :|
